# 기본 프로파일 설정
spring:
  profiles:
    active: local  # 기본 활성 프로파일 (local, dev, prod 중 선택)
  
  # 애플리케이션 이름
  application:
    name: kp-monitor

# 로깅 설정
logging:
  level:
    root: INFO
    com.art.main.kpmonitor: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE